%得到三种篡改方式检测的低频压缩图像及差值图像
clc;
clear all;
%篡改攻击
[I,Ia,Ib,Ic]=attack('wm_lena.bmp',10);
%绘制篡改攻击后的含水印图像
subplot(4,4,1),imshow(I);title('未篡改的图像');
subplot(4,4,5),imshow(Ia);title('篡改内容和水印的图像');
subplot(4,4,9),imshow(Ib);title('篡改内容的图像');
subplot(4,4,13),imshow(Ic);title('篡改水印的图像');
%对篡改图像进行检测
[I1,I2,I3,I1a,I2a,I3a,I1b,I2b,I3b,I1c,I2c,I3c]=detect('wm_lena.bmp',20112685,0.55);
%输出未篡改图像检测的低频压缩图像及差值图像
subplot(4,4,2),imshow(I1*16);title('未篡改的水印低频压缩图像');
subplot(4,4,3),imshow(I2*16);title('未篡改的内容低频压缩图像');
subplot(4,4,4),imshow(I3);title('未篡改的差值低频压缩图像');
%输出篡改了内容和水印的图像检测的低频压缩图像及差值图像
subplot(4,4,6),imshow(I1a*16);title('篡改内容和水印的水印低频压缩图像');
subplot(4,4,7),imshow(I2a*16);title('篡改内容和水印的内容低频压缩图像');
subplot(4,4,8),imshow(I3a);title('篡改内容和水印的差值低频压缩图像');
imwrite(I1a*16,'a_lena_1.bmp');
imwrite(I2a*16,'a_lena_2.bmp');
imwrite(I3a,'a_lena_3.bmp');
%输出篡改了内容的图像检测的低频压缩图像及差值图像
subplot(4,4,10),imshow(I1b*16);title('篡改内容的水印低频压缩图像');
subplot(4,4,11),imshow(I2b*16);title('篡改内容的内容低频压缩图像');
subplot(4,4,12),imshow(I3b);title('篡改内容的差值低频压缩图像');
imwrite(I1b*16,'b_lena_1.bmp');
imwrite(I2b*16,'b_lena_2.bmp');
imwrite(I3b,'b_lena_3.bmp');
%输出篡改了水印的图像检测的低频压缩图像及差值图像
subplot(4,4,14),imshow(I1c*16);title('篡改水印的水印低频压缩图像');
subplot(4,4,15),imshow(I2c*16);title('篡改水印的内容低频压缩图像');
subplot(4,4,16),imshow(I3c);title('篡改水印的差值低频压缩图像');
imwrite(I1c*16,'c_lena_1.bmp');
imwrite(I2c*16,'c_lena_2.bmp');
imwrite(I3c,'c_lena_3.bmp');